### PR TITLE
Adding configurations for AppVeyor and Travis CI

### PR DESCRIPTION
**Pull request by janbernloehr**
To activate AppVeyor builds, login on https://ci.appveyor.com/ and select this repository.
To activate Travis CI builds, login on https://travis-ci.org/ and select this repository.
Both services are free of charge since this is an open source repository.

Finally, you can enable AppVeyor hooks and Travis CI service [here](https://github.com/WordDocX/DocX/settings/hooks) so that github displays the build status next to commits.

### CODE REVIEW

**Comment by janbernloehr** [comment]
Travis seems to be already setup, just appveyor is missing :+1: 
AppVeyor is running builds on Windows which should be the main user base.
Travis is running builds on Ubuntu. There are still some issues on Ubuntu on which I am working at the moment.

**Comment by PrzemyslawKlys** [comment]
Added :-) Travis fails on tests. Appveyor works.

**Comment by janbernloehr** [comment]
Perfect! If you want, you can add the AppVeyor badge to the Readme. You should find the markdown code for the badge here: https://ci.appveyor.com/project/PrzemyslawKlys/docx/settings/badges

**Comment by PrzemyslawKlys** [comment]
Fixed links with proper image for nuget, appveyor and travis ci.

**Pull request merged**
