### PR TITLE
Content and Replacement

### PR DESCRIPTION
**Pull request by cradaydg**
Add Content Control collection and methods to replace text.

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
Can you provide Content.docx that is used within your code so that Examples can work ?

**Comment by cradaydg** [comment]
I think this is the one.

**Comment by PrzemyslawKlys** [comment]
Not sure what you mean? I can't find Content.docx file attached.

**Comment by cradaydg** [comment]
Hmm, could have sworn I attached it. I'll try again tonight.


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Pull request merged**
