### PR TITLE
Working on table

### PR DESCRIPTION
**Pull request by Michalazza**
Fixed insertColumns/removeColumns method along with remove. It is now able to work with merged cells.

Added a method to delete cells

Added gridSpan property to cells

Added gridAfter property to rows

### CODE REVIEW

**Comment by PrzemyslawKlys** [comment]
It does seem things are not building after your commit. Can you verify this?

**Comment by PrzemyslawKlys** [comment]
1) Test Error : UnitTests.DocXUnitTests.Test_Table_InsertColumnWithMergedCells
   System.IO.DirectoryNotFoundException : Could not find a part of the path 'C:\Meh\ThisTest.docx'.   

I would say you need to make changes to this test to not be hardcoded. Also check if you need to submit all Files Changed (some may be unnecessary).

**Comment by Michalazza** [comment]
AppVeyor did not build properly but I'm not sure if that's because I've changed the method parameters for some methods.

**Comment by PrzemyslawKlys** [comment]
It's because of the C:\Meh. You didn't had that in earlier commits, and in last one it appears.

**Comment by Michalazza** [comment]
Yep no worries thought I took that out. I'll do it tomorrow I'm going to sleep now

**Comment by Michalazza** [comment]
Hey man, I've updated the project and it passes the build now. Thanks for telling me the problem with it hopefully you like it.

**Comment by PrzemyslawKlys** [comment]
Ill verify it after the weekend. Thanks. Most likely will need to cleanup the .csproj but other than that it's fine. Thank you.

**Comment by Michalazza** [comment]
Thanks for the feedback. I'll keep working on it and refine it more and pull request if any more changes.

**Pull request merged**
