### PR TITLE
Cross plattform testing

### PR DESCRIPTION
**Pull request by janbernloehr**
Added AppVeyor (building on Windows) and Travis CI (building on ubuntu).
Fixed an issue related to absolute paths fixing #17.
Had to migrate from MSTest to NUnit so that tests can be run on linux.
All tests except ApplyTemplate are passing on ubuntu now.

### CODE REVIEW

**Comment by janbernloehr** [comment]
You can check AppVeyor [Build status](https://ci.appveyor.com/project/janmolnar/docx/branch/master) and Travis CI Travis CI

**Comment by PrzemyslawKlys** [comment]
That's lots of commits considering a lot of different issues. Hard to verify things.

**Comment by janbernloehr** [comment]
I am sorry for the mess. The 3 major parts are:
- migration from MSTest to NUnit
 - Allows unit test execution on linux / osx systems
 - all changes are contained in /UnitTests/*
- Addition of AppVeyor and TravisCI build scripts
 - just two files (appveyor.yml) and (.travis.yml)
- Fix of #17 contained in DocX.cs

If needed I can create three separate pull requests.

**Comment by PrzemyslawKlys** [comment]
I think it's much easier if you separate those things. I looked a bit in the code and there's so much changes that fixing it all may be more than I can handle at one go, especially with conflicts. You also modified .sln heavily which I am afraid will also need to be fixed after everything. Also Travis CI build is failing ;)

**Comment by PrzemyslawKlys** [comment]
Closing  this one, as this one was split into other smaller, cleaner commits.

**Pull request closed without merging**
