### PR TITLE
Added DocX.iOS + iOS Test app

### PR DESCRIPTION
**Pull request by Zambiorix**
Hi,

DocX now works on iOS iPhone & iPad with Xamarin.iOS SDK.
I haven't changed anything in the current code or solution, I just added a new Xamarin solution and an iOS library with references to the existing DocX code. I also added missing code to make it work on iOS.

There is also an iOS test app that runs on iPhone and iPad, creates a sample Word document and shows it in a UIWebView (browser window).

Maybe others can benefit from these projects too, so I created a pull request.

As said, nothing on the original code has changed.

Later on, I'll code the Android version too ...

Cheers

Gerd

### CODE REVIEW

**Comment by Zambiorix** [comment]
It is possible to update the NuGet package so it works in Xamarin (and Visual Studio) to for Mobile projects. But I'm not sure how that works...

**Comment by PrzemyslawKlys** [comment]
Ill try to integrate this next week. As for NuGet we need to ask the person that holds the keys to that. We dont have that as some other person manages that.

**Comment by PrzemyslawKlys** [comment]
Great work btw.

**Comment by PrzemyslawKlys** [comment]
Question... does your code base on DocX library or is it a copy with modifications? What I'm wondering what will happen if commits will be done to main library ? Will it still work on your side or will it require same changes to your iOS part?

**Comment by Zambiorix** [comment]
I forked the original project (this project), made modifications and sent you a pull request. I just added a solution specifically for iOS. I did not change the original code nor the original solution. 

As soon as you accept the pull request I'll merge it again with my forked version and the circle is round :-)

**Pull request merged**
