### PR TITLE
Added the independent Font implementation

### PR DESCRIPTION
**Pull request by mkorsukov**
- New simple Font implementation
- New Font() overload in Paragraph type to accept strings
- Visual Studio default formatting somewhere

### CODE REVIEW

**Comment by mkorsukov** [comment]
Looks like unit tests in Linux is unable to find the Template.dotx. The possible issue is in TestHelper.DirectoryWithFiles.

**Comment by PrzemyslawKlys** [comment]
Doest this have any impact ? As in it works exactly the same as the old implementation but supports linux as well ?

**Comment by mkorsukov** [comment]
You are right. That is simple Font replacement (the next one is Color). If you disagree you can easily reject the commit :)

**Comment by PrzemyslawKlys** [comment]
Nah, no need to.

**Pull request merged**
